import { NewsStory } from './types'

export const INITIAL_STORIES: NewsStory[] = [
  {
    id: 'story-trending-1',
    title: 'Next-Generation Autonomous AI Systems Begin Outperforming Human Experts Across Major Industries',
    slug: 'next-gen-autonomous-ai-systems-outperforming-human-experts',
    simplifiedTitle: 'Next-Gen AI Systems Are Taking Off: What It Actually Means For You',
    source: 'Tech & AI Wire',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    timeAgo: '20m ago',
    category: 'tech',
    categoryLabel: 'AI & Tech',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'The newest wave of autonomous agentic AI models has demonstrated breakthrough capabilities in complex reasoning, software engineering, and continuous data synthesis, sparking massive worldwide adoption and debate.',
    bigPicture:
      'The newest generation of AI models can now handle complex, multi-step tasks completely on their own, transforming how everyday tools and businesses run.',
    whatHappened: [
      'Leading AI research labs released advanced autonomous models capable of executing hours of complex problem-solving without getting stuck.',
      'Unlike older chatbots that only answered questions, these new systems can browse, analyze data, and build full solutions end-to-end.',
      'Major tech companies are racing to integrate these tools into phones, computers, and everyday apps to handle chores automatically.',
    ],
    whyItMatters:
      'This technology will speed up everyday online tasks and make helpful automated assistants accessible to anyone with a smartphone.',
    plainWords: [
      { word: 'Autonomous Agent', meaning: 'An AI that can make its own step-by-step decisions to complete a whole project from start to finish.' },
      { word: 'Reasoning Model', meaning: 'An AI designed to pause and think through tricky problems before giving an answer.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 99,
    state: 'california',
    city: 'san francisco',
    coordinates: [-119.4, 36.8],
  },
  {
    id: 'story-trending-2',
    title: 'James Webb Space Telescope Uncovers Surprising Atmospheric Clues on Earth-Sized Exoplanet',
    slug: 'james-webb-telescope-detects-atmosphere-earth-sized-planet',
    simplifiedTitle: 'NASA Space Telescope Detects Clues of Atmosphere on Earth-Sized World',
    source: 'Space & Discoveries',
    sourceUrl: 'https://nasa.gov',
    pubDate: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    timeAgo: '45m ago',
    category: 'science',
    categoryLabel: 'Space & Science',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'Deep-space spectroscopic observations from NASA\'s James Webb Space Telescope have revealed unprecedented thermal patterns on an Earth-sized exoplanet, offering the strongest evidence yet of a planetary atmosphere outside our solar system.',
    bigPicture:
      'Astronomers using the James Webb Space Telescope have uncovered evidence that a rocky planet outside our solar system may actually hold an atmosphere.',
    whatHappened: [
      'The James Webb telescope pointed its ultra-sensitive infrared sensors at a rocky world 40 light-years away.',
      'The data showed temperatures on the planet\'s night side are being circulated, which normally only happens when an atmosphere traps heat.',
      'Scientists are now scheduling follow-up observations to analyze the exact gases present in the planet\'s skies.',
    ],
    whyItMatters:
      'Finding atmospheres on rocky worlds brings humanity one step closer to understanding whether life could exist elsewhere in the universe.',
    plainWords: [
      { word: 'Exoplanet', meaning: 'Any planet that orbits a distant star outside our own solar system.' },
      { word: 'Infrared Sensors', meaning: 'Special cameras that see heat radiation instead of visible light.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 95,
    state: 'florida',
    city: 'cape canaveral',
    coordinates: [-81.5, 27.6],
  },
  {
    id: 'story-trending-3',
    title: 'New Entertainment Phenomenon Shatters All-Time Global Streaming Records in Opening Weekend',
    slug: 'entertainment-phenomenon-shatters-global-streaming-records',
    simplifiedTitle: 'Viral Hit Show Breaks All-Time Global Streaming Viewership Records',
    source: 'Pop Culture Wire',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    timeAgo: '1h ago',
    category: 'entertainment',
    categoryLabel: 'Pop Culture',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'An unexpected breakout series has shattered international streaming records, racking up over 110 million views across 90 countries in just its first 72 hours of release.',
    bigPicture:
      'A surprise breakout entertainment series has captured worldwide attention, becoming the most-watched debut in streaming history.',
    whatHappened: [
      'The new show debuted simultaneously in over 90 countries and went viral immediately across TikTok, YouTube, and X.',
      'Over 110 million viewers tuned in over the weekend, beating the previous all-time record set in 2024.',
      'Creators announced that fan interest has already triggered plans for extended seasons and spin-off specials.',
    ],
    whyItMatters:
      'It shows how fast modern internet culture can turn an underdog creative project into a global phenomenon in a matter of hours.',
    plainWords: [
      { word: 'Streaming Debut', meaning: 'The very first weekend a new show is released on digital video platforms.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 92,
    state: 'california',
    city: 'los angeles',
    coordinates: [-119.4, 36.8],
  },
  {
    id: 'story-trending-4',
    title: 'Major Stock Indexes Surge to Fresh All-Time Highs as Global Productivity Accelerates',
    slug: 'stock-indexes-surge-to-all-time-highs-global-productivity',
    simplifiedTitle: 'Stock Markets Hit Record Highs: Why Portfolios and 401ks Are Surging',
    source: 'Markets & Economy',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    timeAgo: '2h ago',
    category: 'money',
    categoryLabel: 'Money & Markets',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'Broad equity markets rallied to record territory as cooling inflation prints combined with unprecedented corporate productivity gains from technology investment propelled major indexes higher.',
    bigPicture:
      'Stock markets have climbed to new record peaks as everyday inflation cools down and corporate earnings beat expectations.',
    whatHappened: [
      'The S&P 500, Dow Jones, and Nasdaq all crossed new all-time milestones during strong trading this week.',
      'Inflation numbers came in lower than anticipated, easing pressure on consumer interest rates and borrowing costs.',
      'Retirement accounts and index fund portfolios saw widespread balance boosts across the country.',
    ],
    whyItMatters:
      'A strong market boosts 401(k) retirement funds and investments, giving people more financial flexibility and confidence.',
    plainWords: [
      { word: 'Index Fund', meaning: 'A simple investment bucket that tracks hundreds of top companies at once.' },
      { word: 'Inflation Cooling', meaning: 'Prices are stopping their rapid climb and returning to normal, steady rates.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 89,
    state: 'new york',
    city: 'nyc',
    coordinates: [-74.2, 43.3],
  },
  {
    id: 'story-trending-5',
    title: 'Historic Late-Game Rally Crowns New Champions in Thrilling Overtime Finish',
    slug: 'historic-late-game-rally-crowns-champions-thrilling-overtime',
    simplifiedTitle: 'Unbelievable Overtime Rally Sparks One of Sports\' Greatest Comebacks',
    source: 'Sports Wire',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    timeAgo: '2h ago',
    category: 'sports',
    categoryLabel: 'Sports & Records',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'In a championship decider that will be remembered for decades, an underdog team rallied from an improbable deficit in the final minutes to capture the title in sudden-death overtime.',
    bigPicture:
      'An underdog team mounted an unforgettable late rally, overcoming near-impossible odds to win the championship in overtime.',
    whatHappened: [
      'Trailing by multiple scores with only minutes left on the clock, the underdogs mounted a flawless scoring run.',
      'A game-tying play with just seconds remaining sent the stadium and millions of television viewers into absolute pandemonium.',
      'In sudden-death overtime, a legendary defensive play sealed the historic victory.',
    ],
    whyItMatters:
      'It is being celebrated as an instant classic that will be replayed in sports highlight reels for generations to come.',
    plainWords: [
      { word: 'Sudden-Death Overtime', meaning: 'Extra playing time where the very first team to score wins the entire game instantly.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 86,
    state: 'texas',
    city: 'dallas',
    coordinates: [-99.9, 31.1],
  },
  {
    id: 'story-trending-6',
    title: 'Massive Ocean Cleanup and Barrier Reef Restoration Projects Cross Milestone Years Ahead of Schedule',
    slug: 'ocean-cleanup-barrier-reef-restoration-milestone-ahead-of-schedule',
    simplifiedTitle: 'Historic Ocean Clean-Up Milestone Achieved Years Ahead of Schedule',
    source: 'Good News Network',
    sourceUrl: 'https://goodnewsnetwork.org',
    pubDate: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    timeAgo: '3h ago',
    category: 'good-news',
    categoryLabel: 'Good News',
    imageUrl: 'https://images.unsplash.com/photo-1426604966848-d7adac402bff?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'International marine recovery coalitions announced today that modern automated collection fleets and coral micro-fragmentation technologies have restored record stretches of coastal marine life.',
    bigPicture:
      'Autonomous cleanup ships and global conservation teams have cleared millions of pounds of plastic and revitalized damaged coral reefs ahead of target dates.',
    whatHappened: [
      'Specially designed solar-powered collection vessels removed over 5 million pounds of waste from critical ocean zones.',
      'Marine biologists successfully planted thousands of heat-resilient coral fragments that grew 25 times faster than natural rates.',
      'Key marine species and sea turtle populations have begun returning to protected coastal habitats.',
    ],
    whyItMatters:
      'This proves that modern technology and global teamwork can actively reverse environmental damage and protect marine ecosystems.',
    plainWords: [
      { word: 'Micro-Fragmentation', meaning: 'A scientific technique that splits coral into tiny pieces so it grows dozens of times faster.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 83,
    state: 'hawaii',
    city: 'honolulu',
    coordinates: [-155.5, 19.9],
  },
  {
    id: 'story-trending-7',
    title: 'Pacific Northwest Clean Energy Grid Breaks Historic All-Time Output Record',
    slug: 'pacific-northwest-clean-energy-record',
    simplifiedTitle: 'Pacific Northwest Power Grid Runs 100% On Renewable Energy This Week',
    source: 'Clean Energy Wire',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    timeAgo: '3h ago',
    category: 'science',
    categoryLabel: 'Space & Science',
    imageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'Hydroelectric, wind, and next-generation battery reserves across Washington and Oregon powered the regional electric grid without fossil fuels for seven consecutive days.',
    bigPicture:
      'The Pacific Northwest just proved that major metropolitan regions can power factories, cities, and homes entirely through clean energy without blackouts.',
    whatHappened: [
      'Combined hydro dams, coastal wind arrays, and grid-scale battery parks met 100% of consumer peak demand.',
      'Utility providers reported electricity bills for households will see an estimated 8% seasonal rate decrease.',
      'Other regional power authorities are now copying the Northwest management model for their summer grids.',
    ],
    whyItMatters:
      'Clean energy is proving reliable and cheaper for everyday families, reducing monthly utility bills while cutting pollution.',
    plainWords: [
      { word: 'Grid Storage', meaning: 'Massive neighborhood battery banks that store excess power for use during peak hours.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 85,
    state: 'washington',
    city: 'seattle',
    coordinates: [-120.7, 47.7],
  },
  {
    id: 'story-trending-8',
    title: 'Major Semiconductor and Tech Manufacturing Hub Opens in Midwest Corridor',
    slug: 'midwest-semiconductor-manufacturing-hub-opens',
    simplifiedTitle: 'Huge Midwest Tech Factory Opens: 7,000 New Skilled Jobs Coming to Ohio',
    source: 'Economy Wire',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    timeAgo: '4h ago',
    category: 'money',
    categoryLabel: 'Money & Markets',
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'A multi-billion dollar domestic chip fabrication facility has opened its first production phase in central Ohio, anchoring high-tech manufacturing inside the American heartland.',
    bigPicture:
      'A brand new advanced microchip plant has officially opened in Ohio, creating thousands of high-paying jobs and strengthening US manufacturing.',
    whatHappened: [
      'Phase one of the massive campus was completed on time, employing local trade workers and specialized engineers.',
      'The facility will produce chips used in American automobiles, home appliances, and medical devices.',
      'Community colleges in the area have launched tuition-free certification programs to train local high school graduates.',
    ],
    whyItMatters:
      'Building critical technology in America keeps consumer goods affordable and creates steady career opportunities outside the coasts.',
    plainWords: [
      { word: 'Semiconductor Fabrication', meaning: 'A high-tech factory that manufactures the microscopic computer chips inside phones and cars.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 88,
    state: 'ohio',
    city: 'columbus',
    coordinates: [-82.9, 40.4],
  },
  {
    id: 'story-trending-9',
    title: 'New High-Speed Clean Passenger Rail Corridor Approved Linking Great Lakes Metros',
    slug: 'great-lakes-high-speed-clean-passenger-rail',
    simplifiedTitle: 'High-Speed Electric Train Line Approved to Connect Chicago and Midwest Hubs',
    source: 'Transportation Daily',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    timeAgo: '4h ago',
    category: 'living',
    categoryLabel: 'Everyday Life',
    imageUrl: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'Federal and state transportation authorities have finalized funding for an electrified passenger rail corridor connecting Illinois, Indiana, and Michigan with 160 mph speeds.',
    bigPicture:
      'Midwest commuters will soon be able to travel between major cities in under two hours aboard modern electric bullet trains.',
    whatHappened: [
      'The new transit link will cut travel times between Chicago and regional economic hubs by more than half.',
      'Tickets are designed to be competitive with highway gas costs, giving families an affordable travel alternative.',
      'Construction kicks off this spring, generating thousands of infrastructure jobs.',
    ],
    whyItMatters:
      'Fast, affordable regional transit means less traffic congestion, lower gas expenses, and easier weekend family visits.',
    plainWords: [
      { word: 'Electrified Corridor', meaning: 'Train tracks powered entirely by overhead clean electric lines rather than diesel fuel.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 81,
    state: 'illinois',
    city: 'chicago',
    coordinates: [-89.4, 40.6],
  },
  {
    id: 'story-trending-10',
    title: 'Atlanta Research Hospital Unveils Fast Non-Invasive Cardiac Health Scanner',
    slug: 'atlanta-research-hospital-cardiac-scanner',
    simplifiedTitle: 'Breakthrough 3-Minute Heart Scanner Can Detect Issues Years in Advance',
    source: 'Health & Wellness',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    timeAgo: '5h ago',
    category: 'health',
    categoryLabel: 'Health & Wellness',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'Cardiologists in Georgia have completed human clinical trials on a high-speed acoustic scanner that spots arterial plaque without needles, radiation, or invasive dyes.',
    bigPicture:
      'Doctors have developed a painless 3-minute scan that can catch early heart disease before symptoms ever show up.',
    whatHappened: [
      'The scanner uses gentle ultrasound frequencies to map blood flow and artery flexibility in minutes.',
      'Patients simply lay comfortably while a doctor moves a soft wand over their chest.',
      'The FDA granted expedited review so clinics nationwide can begin offering the test by late autumn.',
    ],
    whyItMatters:
      'Catching heart issues early lets people make simple diet and exercise adjustments before needing surgery or heavy medication.',
    plainWords: [
      { word: 'Non-Invasive', meaning: 'A medical test that does not require needles, surgery, or entering the body.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 90,
    state: 'georgia',
    city: 'atlanta',
    coordinates: [-83.5, 32.2],
  },
  {
    id: 'story-trending-11',
    title: 'Historic Keystone Rail and Road Modernization Delivers Smooth Commutes in Pennsylvania',
    slug: 'pennsylvania-keystone-infrastructure-milestone',
    simplifiedTitle: 'Pennsylvania Completes Landmark Bridge and Highway Upgrade Ahead of Winter',
    source: 'Mid-Atlantic Wire',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    timeAgo: '6h ago',
    category: 'living',
    categoryLabel: 'Everyday Life',
    imageUrl: 'https://images.unsplash.com/photo-1545459720-aac8509eb02c?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'The Pennsylvania Department of Transportation announced the full reopening of key highway and rail interchanges with modern cold-weather resilient asphalt and smart traffic sensors.',
    bigPicture:
      'Crucial transit arteries connecting Philadelphia, Pittsburgh, and rural towns have reopened with smoother roads and modern safety guardrails.',
    whatHappened: [
      'Crews completed multi-mile road resurfacing weeks ahead of winter freeze cycles.',
      'New smart pavement sensors will automatically warn highway dispatchers when black ice starts forming.',
      'Toll rates along the upgraded sections are frozen for the upcoming year.',
    ],
    whyItMatters:
      'Safer, smoother roads mean fewer car repair bills, fewer winter accidents, and less time stuck in traffic delays.',
    plainWords: [
      { word: 'Smart Pavement', meaning: 'Roads embedded with tiny weather sensors that detect freezing conditions in real time.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 78,
    state: 'pennsylvania',
    city: 'philadelphia',
    coordinates: [-77.2, 41.2],
  },
  {
    id: 'story-trending-12',
    title: '2026 Social Security Benefits and Medicare Cost Adjustments Explained in Plain English',
    slug: '2026-social-security-benefits-plain-english-breakdown',
    simplifiedTitle: '2026 Social Security Check Adjustments: Exactly What to Expect in Plain English',
    source: 'National Policy Desk',
    sourceUrl: 'https://news.google.com',
    pubDate: new Date(Date.now() - 1000 * 60 * 400).toISOString(),
    timeAgo: '6h ago',
    category: 'us-world',
    categoryLabel: 'US & World',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
    originalSummary:
      'Federal retirement administrators have finalized the annual cost-of-living adjustment (COLA) formula, raising average monthly checks while keeping Medicare Part B deductibles stable.',
    bigPicture:
      'Monthly Social Security payments will increase starting next quarter to help everyday Americans keep up with household expenses.',
    whatHappened: [
      'The official annual adjustment will add an estimated $50 to $75 per month to the typical retirement check.',
      'Medicare Part B premiums will remain virtually unchanged, meaning recipients keep the majority of their increase.',
      'Personalized notices will be mailed and viewable online through official government portals next month.',
    ],
    whyItMatters:
      'Knowing exactly how much your check will increase helps you budget confidently for groceries, heating, and prescriptions.',
    plainWords: [
      { word: 'COLA', meaning: 'Cost of Living Adjustment — an automatic yearly boost to make sure checks keep up with everyday grocery and utility bills.' },
      { word: 'Deductible', meaning: 'The small upfront amount you pay for medical care before insurance covers the rest.' },
    ],
    readTimeMinutes: 2,
    trendingScore: 94,
    state: 'district of columbia',
    city: 'washington dc',
    coordinates: [-77.0, 38.9],
  },
]
